name: Test Action

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Sample job
    steps:
      - uses: actions/checkout@v3
        with:
          repository: SohraubP/test-yaml-read@main
          path: ./configs
      - name: Check
        run: cat ./configs/config_test.yml
